# Stellar Classification Pipeline Configuration
dataset:
  name: "stellar_classification"
  source: "Sloan Digital Sky Survey DR17"
  data_path: "data/raw/star_classification.csv"
  target_column: "class"
  test_size: 0.2
  random_state: 42

data:
  target_column: "class"
  feature_columns:
    - "u"
    - "g" 
    - "r"
    - "i"
    - "z"
    - "specobjid"
    - "redshift"
    - "plate"
    - "mjd"
    - "fiberid"
  class_mapping:
    "GALAXY": 0
    "STAR": 1
    "QSO": 2

preprocessing:
  handle_missing: true
  remove_outliers: true
  outlier_method: "lof"
  outlier_threshold: 0.1

feature_engineering:
  create_color_indices: true
  scale_features: true

models:
  svm:
    kernel: "rbf"
    C: 1
    gamma: "scale"
    random_state: 42
  random_forest:
    n_estimators: 100
    max_depth: 10
    random_state: 42
  xgboost:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    random_state: 42

# Classes configuration
classes:
  labels: ["GALAXY", "STAR", "QSO"]
  num_classes: 3

# MLflow experiment tracking
mlflow:
  experiment_name: "stellar_classification"
  tracking_uri: "http://mlflow:5000"
  artifact_location: "/opt/mlflow/artifacts"

# Training configuration
training:
  test_size: 0.2
  random_state: 42
  cross_validation_folds: 5
  hyperparameter_tuning: true

# Evaluation metrics
evaluation:
  metrics:
    - "accuracy"
    - "precision"
    - "recall" 
    - "f1_score"
  plot_confusion_matrix: true
  plot_roc_curves: true